import os
import shutil
import sqlite3
import uuid
import traceback
from pathlib import Path
from datetime import datetime, timedelta
import sqlite3
import pandas as pd

from pyspark.sql import SparkSession
from pyspark.sql.functions import (
    col,
    trim,
    initcap,
    when,
    to_date,
    datediff,
    current_timestamp,
    lit,
)


# ============================================================
# 1. PROJECT PATHS
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parent.parent

SOURCE_FILE = PROJECT_ROOT / "data" / "raw" / "shipments.csv"

OUTPUT_ROOT = PROJECT_ROOT / "data" / "output"

# Old target.
# We NEVER delete or rename this folder.
LEGACY_TARGET_FOLDER = OUTPUT_ROOT / "target_shipments"

# New versioned target.
TARGET_VERSIONS_FOLDER = (
    OUTPUT_ROOT / "target_shipments_versions"
)

# Pointer to currently active target.
LATEST_TARGET_POINTER = (
    OUTPUT_ROOT / "latest_target.txt"
)

# Invalid records.
INVALID_VERSIONS_FOLDER = (
    OUTPUT_ROOT / "invalid_shipments_versions"
)

LATEST_INVALID_POINTER = (
    OUTPUT_ROOT / "latest_invalid.txt"
)

# Temporary folders.
TEMP_ROOT = OUTPUT_ROOT / "_temp"

# SQLite audit database.
AUDIT_DB = (
    PROJECT_ROOT
    / "data"
    / "logs"
    / "etl_audit.db"
)


# ============================================================
# 2. SETTINGS
# ============================================================

PARTITION_THRESHOLD = 30

LARGE_DATASET_PARTITIONS = 2

VERSION_RETENTION = 3

SOURCE_FORMAT = "csv"


# ============================================================
# 3. REQUIRED SOURCE COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "ShipmentID",
    "Customer",
    "City",
    "Weight",
    "Status",
    "ShipmentDate",
    "DeliveryDate",
    "ShippingCost",
]


# ============================================================
# 4. BUSINESS COLUMNS USED FOR CHANGE DETECTION
# ============================================================

# IMPORTANT:
#
# These are the actual source/business fields.
#
# We intentionally do NOT compare:
#
# Weight_Category
# DeliveryDays
# WeightStatus
# ProcessedDate
#
# because those are generated by the ETL itself.

COMPARE_COLUMNS = [
    "Customer",
    "City",
    "Weight",
    "Status",
    "ShipmentDate",
    "DeliveryDate",
    "ShippingCost",
]


# ============================================================
# 5. CREATE DIRECTORIES
# ============================================================

OUTPUT_ROOT.mkdir(
    parents=True,
    exist_ok=True
)

TARGET_VERSIONS_FOLDER.mkdir(
    parents=True,
    exist_ok=True
)

INVALID_VERSIONS_FOLDER.mkdir(
    parents=True,
    exist_ok=True
)

TEMP_ROOT.mkdir(
    parents=True,
    exist_ok=True
)

AUDIT_DB.parent.mkdir(
    parents=True,
    exist_ok=True
)


# ============================================================
# 6. SPARK SESSION
# ============================================================

spark = (
    SparkSession.builder
    .appName("Modern-DE-ETL")
    .master("local[2]")
    .getOrCreate()
)

spark.sparkContext.setLogLevel("WARN")


# ============================================================
# 7. RUN ID
# ============================================================

RUN_ID = str(uuid.uuid4())

START_TIME = datetime.now()


print()
print("=" * 70)
print("MODERN DATA ENGINEERING ETL")
print("=" * 70)

print(f"Run ID    : {RUN_ID}")
print(f"Start Time: {START_TIME}")

print("=" * 70)


# ============================================================
# 8. AUDIT DATABASE
# ============================================================

def initialize_audit_db():
    '''
    Creates the audit table if it does not exist.

    Also safely migrates the older audit-table schema used by
    the previous version of this project. Existing audit history
    is preserved; missing columns are added automatically.
    '''

    AUDIT_DB.parent.mkdir(parents=True, exist_ok=True)

    conn = sqlite3.connect(AUDIT_DB)
    cursor = conn.cursor()

    cursor.execute(
        '''
        CREATE TABLE IF NOT EXISTS etl_audit_log
        (
            RunID TEXT PRIMARY KEY,
            StartTime TEXT,
            EndTime TEXT,
            Status TEXT,
            InsertedRecords INTEGER DEFAULT 0,
            UpdatedRecords INTEGER DEFAULT 0,
            UnchangedRecords INTEGER DEFAULT 0,
            ValidRecords INTEGER DEFAULT 0,
            InvalidRecords INTEGER DEFAULT 0,
            DurationSeconds REAL DEFAULT 0,
            ErrorMessage TEXT
        )
        '''
    )

    # --------------------------------------------------------
    # Migrate an existing older audit table.
    # CREATE TABLE IF NOT EXISTS does not alter an existing
    # SQLite table, so add missing columns explicitly.
    # --------------------------------------------------------

    cursor.execute("PRAGMA table_info(etl_audit_log)")
    existing_columns = {
        row[1]
        for row in cursor.fetchall()
    }

    required_columns = {
        "RunID": "TEXT",
        "StartTime": "TEXT",
        "EndTime": "TEXT",
        "Status": "TEXT",
        "InsertedRecords": "INTEGER",
        "UpdatedRecords": "INTEGER",
        "UnchangedRecords": "INTEGER",
        "ValidRecords": "INTEGER",
        "InvalidRecords": "INTEGER",
        "DurationSeconds": "REAL",
        "ErrorMessage": "TEXT",
    }

    for column_name, data_type in required_columns.items():

        if column_name not in existing_columns:

            cursor.execute(
                f'ALTER TABLE etl_audit_log '
                f'ADD COLUMN "{column_name}" {data_type}'
            )

    # Preserve counts from the old audit schema.
    old_to_new = {
        "Inserted": "InsertedRecords",
        "Updated": "UpdatedRecords",
        "Unchanged": "UnchangedRecords",
    }

    for old_column, new_column in old_to_new.items():

        if old_column in existing_columns:

            cursor.execute(
                f'''
                UPDATE etl_audit_log
                SET "{new_column}" =
                    COALESCE("{new_column}", "{old_column}")
                WHERE "{new_column}" IS NULL
                '''
            )

    # --------------------------------------------------------
    # Detailed change history.
    # One row is stored for each changed source/business column.
    # --------------------------------------------------------

    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS etl_change_history
        (
            ChangeID TEXT PRIMARY KEY,
            RunID TEXT,
            ChangeTime TEXT,
            ShipmentID TEXT,
            ColumnName TEXT,
            OldValue TEXT,
            NewValue TEXT
        )
        """
    )

    conn.commit()
    conn.close()


initialize_audit_db()


# ============================================================
# 9. START AUDIT
# ============================================================

def start_audit():

    conn = sqlite3.connect(AUDIT_DB)

    cursor = conn.cursor()

    cursor.execute(
        """
        INSERT INTO etl_audit_log
        (
            RunID,
            StartTime,
            Status
        )
        VALUES (?, ?, ?)
        """,
        (
            RUN_ID,
            START_TIME.isoformat(),
            "RUNNING"
        )
    )

    conn.commit()

    conn.close()


start_audit()


# ============================================================
# 10. UPDATE AUDIT
# ============================================================

def update_audit(
    status,
    inserted=0,
    updated=0,
    unchanged=0,
    valid=0,
    invalid=0,
    duration=0,
    error_message=None
):

    conn = sqlite3.connect(AUDIT_DB)

    cursor = conn.cursor()

    end_time = datetime.now()

    cursor.execute(
        """
        UPDATE etl_audit_log
        SET
            EndTime = ?,
            Status = ?,
            InsertedRecords = ?,
            UpdatedRecords = ?,
            UnchangedRecords = ?,
            ValidRecords = ?,
            InvalidRecords = ?,
            DurationSeconds = ?,
            ErrorMessage = ?
        WHERE RunID = ?
        """,
        (
            end_time.isoformat(),
            status,
            inserted,
            updated,
            unchanged,
            valid,
            invalid,
            duration,
            error_message,
            RUN_ID
        )
    )

    conn.commit()

    conn.close()


# ============================================================
# 11. SAVE DETAILED CHANGE HISTORY
# ============================================================

def save_change_history(change_rows):

    if not change_rows:
        return

    conn = sqlite3.connect(AUDIT_DB)

    cursor = conn.cursor()

    for row in change_rows:

        cursor.execute(
            """
            INSERT INTO etl_change_history
            (
                ChangeID,
                RunID,
                ChangeTime,
                ShipmentID,
                ColumnName,
                OldValue,
                NewValue
            )
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (
                str(uuid.uuid4()),
                RUN_ID,
                datetime.now().isoformat(),
                str(row["ShipmentID"]),
                row["ColumnName"],
                row["OldValue"],
                row["NewValue"]
            )
        )

    conn.commit()
    conn.close()

    print(
        f"Change history saved: {len(change_rows)} changes."
    )

def export_audit_csvs():
    """
    Export SQLite audit tables to CSV files for Power BI.
    """

    conn = sqlite3.connect(AUDIT_DB)

    try:
        audit_df = pd.read_sql_query(
            "SELECT * FROM etl_audit_log",
            conn
        )

        change_df = pd.read_sql_query(
            "SELECT * FROM etl_change_history",
            conn
        )

        audit_df.to_csv(
            r"D:\Modern-DE-Project\data\logs\etl_audit.csv",
            index=False
        )

        change_df.to_csv(
            r"D:\Modern-DE-Project\data\logs\etl_change_history.csv",
            index=False
        )

        print("Audit CSV files exported successfully.")

    finally:
        conn.close()


# ============================================================
# 11. CLEAN OLD AUDIT LOGS
# ============================================================

def cleanup_old_audit_logs():

    try:

        conn = sqlite3.connect(AUDIT_DB)

        cursor = conn.cursor()

        cutoff = (
            datetime.now()
            - timedelta(days=90)
        )

        cursor.execute(
            """
            DELETE FROM etl_audit_log
            WHERE StartTime < ?
            """,
            (
                cutoff.isoformat(),
            )
        )

        conn.commit()

        conn.close()

        print("Old audit records cleaned.")

    except Exception as e:

        print(
            f"Warning: Could not clean old "
            f"audit records: {e}"
        )


# ============================================================
# 12. FIND CURRENT TARGET
# ============================================================

def get_current_target_folder():

    """
    Finds the target used as the baseline.

    Priority:

    1. latest_target.txt
    2. newest versioned target
    3. old target_shipments
    4. no target
    """

    # --------------------------------------------------------
    # OPTION 1
    # Pointer
    # --------------------------------------------------------

    if LATEST_TARGET_POINTER.exists():

        try:

            target_path = Path(
                LATEST_TARGET_POINTER.read_text(
                    encoding="utf-8"
                ).strip()
            )

            if target_path.exists():

                print()
                print("Current target:")
                print(target_path)

                return target_path

        except Exception as e:

            print(
                "Warning: Could not read "
                f"latest target pointer: {e}"
            )


    # --------------------------------------------------------
    # OPTION 2
    # Newest version
    # --------------------------------------------------------

    versions = [
        p
        for p in TARGET_VERSIONS_FOLDER.iterdir()
        if p.is_dir()
    ]

    if versions:

        versions.sort(
            key=lambda p: p.stat().st_mtime,
            reverse=True
        )

        newest = versions[0]

        print()
        print("Current target:")
        print(newest)

        return newest


    # --------------------------------------------------------
    # OPTION 3
    # Legacy target
    # --------------------------------------------------------

    if LEGACY_TARGET_FOLDER.exists():

        print()
        print("Using existing legacy target:")
        print(LEGACY_TARGET_FOLDER)

        return LEGACY_TARGET_FOLDER


    # --------------------------------------------------------
    # OPTION 4
    # First run
    # --------------------------------------------------------

    print()
    print("No existing target found.")
    print("This will be treated as the first ETL run.")

    return None


# ============================================================
# 13. CHECK TARGET SCHEMA
# ============================================================

def target_schema_is_compatible(target_df):

    """
    Checks whether the existing target contains
    all columns required by the new 8-column design.

    This is important because the project previously
    used a 5-column source/target.
    """

    if target_df is None:

        return False

    required_target_columns = (
        ["ShipmentID"]
        + COMPARE_COLUMNS
    )

    missing_columns = [
        column_name
        for column_name in required_target_columns
        if column_name not in target_df.columns
    ]

    if missing_columns:

        print()
        print("Existing target schema is OLD.")

        print(
            "Missing columns:"
        )

        for column_name in missing_columns:

            print(
                f"  - {column_name}"
            )

        print()
        print(
            "The ETL will automatically rebuild "
            "the baseline using the current "
            "8-column source."
        )

        return False

    print()
    print(
        "Existing target schema is compatible."
    )

    return True


# ============================================================
# 14. WRITE POINTER
# ============================================================

def write_pointer(
    pointer_file,
    target_folder
):

    """
    Safely updates the pointer file.

    The actual target folder is never modified.
    """

    temp_pointer = pointer_file.with_suffix(
        ".tmp"
    )

    temp_pointer.write_text(
        str(target_folder.resolve()),
        encoding="utf-8"
    )

    os.replace(
        temp_pointer,
        pointer_file
    )


# ============================================================
# 15. CLEAN OLD VERSIONED TARGETS
# ============================================================

def cleanup_old_versions(
    folder,
    retention
):

    try:

        versions = [
            p
            for p in folder.iterdir()
            if p.is_dir()
        ]

        versions.sort(
            key=lambda p: p.stat().st_mtime,
            reverse=True
        )

        old_versions = versions[retention:]

        for old in old_versions:

            try:

                shutil.rmtree(old)

                print(
                    f"Removed old version: "
                    f"{old.name}"
                )

            except Exception as e:

                print(
                    f"Warning: Could not remove "
                    f"{old.name}: {e}"
                )

    except Exception as e:

        print(
            f"Warning: Version cleanup failed: {e}"
        )


# ============================================================
# 16. READ SOURCE
# ============================================================

def read_source():

    print()
    print("Reading source file:")
    print(SOURCE_FILE)

    if not SOURCE_FILE.exists():

        raise RuntimeError(
            f"Source file does not exist: "
            f"{SOURCE_FILE}"
        )

    df = (
        spark.read
        .option("header", True)
        .option("inferSchema", True)
        .csv(str(SOURCE_FILE))
    )

    # --------------------------------------------------------
    # Validate required columns
    # --------------------------------------------------------

    missing_columns = [
        column_name
        for column_name in REQUIRED_COLUMNS
        if column_name not in df.columns
    ]

    if missing_columns:

        raise RuntimeError(
            "Missing required columns: "
            + ", ".join(missing_columns)
        )

    print()
    print(
        f"Source records: {df.count()}"
    )

    return df


# ============================================================
# 17. CLEAN AND TRANSFORM
# ============================================================

def transform_data(df):

    print()
    print(
        "Cleaning and transforming data..."
    )

    df = (
        df

        # ----------------------------------------------------
        # Clean Customer
        # ----------------------------------------------------

        .withColumn(
            "Customer",
            initcap(
                trim(
                    col("Customer")
                )
            )
        )

        # ----------------------------------------------------
        # Clean City
        # ----------------------------------------------------

        .withColumn(
            "City",
            initcap(
                trim(
                    col("City")
                )
            )
        )

        # ----------------------------------------------------
        # Clean Status
        # ----------------------------------------------------

        .withColumn(
            "Status",
            initcap(
                trim(
                    col("Status")
                )
            )
        )

        # ----------------------------------------------------
        # Convert ShipmentDate
        # ----------------------------------------------------

        .withColumn(
            "ShipmentDate",
            to_date(
                col("ShipmentDate"),
                "yyyy-MM-dd"
            )
        )

        # ----------------------------------------------------
        # Convert DeliveryDate
        # ----------------------------------------------------

        .withColumn(
            "DeliveryDate",
            to_date(
                col("DeliveryDate"),
                "yyyy-MM-dd"
            )
        )

        # ----------------------------------------------------
        # Calculate DeliveryDays
        # ----------------------------------------------------

        .withColumn(
            "DeliveryDays",
            datediff(
                col("DeliveryDate"),
                col("ShipmentDate")
            )
        )

        # ----------------------------------------------------
        # Weight Category
        # ----------------------------------------------------

        .withColumn(
            "Weight_Category",
            when(
                col("Weight") > 10,
                "Heavy"
            ).otherwise(
                "Normal"
            )
        )

        # ----------------------------------------------------
        # Weight Validation
        # ----------------------------------------------------

        .withColumn(
            "WeightStatus",
            when(
                col("Weight") > 0,
                "Valid"
            ).otherwise(
                "Invalid"
            )
        )

        # ----------------------------------------------------
        # Processing Timestamp
        # ----------------------------------------------------

        .withColumn(
            "ProcessedDate",
            current_timestamp()
        )
    )

    return df


# ============================================================
# 18. READ EXISTING TARGET
# ============================================================

def read_existing_target(target_folder):

    if target_folder is None:

        return None

    print()
    print("Reading existing target:")
    print(target_folder)

    target_df = spark.read.parquet(
        str(target_folder)
    )

    return target_df


# ============================================================
# 19. INCREMENTAL PROCESSING
# ============================================================

def process_incremental(
    source_df,
    target_df
):

    """
    Returns:

        final_df
        inserted_count
        updated_count
        unchanged_count
        change_history_df
    """

    # ========================================================
    # FIRST RUN / SCHEMA MIGRATION
    # ========================================================

    if target_df is None:

        print()
        print(
            "No compatible target found."
        )

        print(
            "Current source will become "
            "the new baseline."
        )

        inserted_count = source_df.count()

        return (
            source_df,
            inserted_count,
            0,
            0,
            None
        )


    # ========================================================
    # INSERTED RECORDS
    # ========================================================

    inserted_df = (
        source_df.alias("src")
        .join(
            target_df.alias("tgt"),
            col("src.ShipmentID")
            ==
            col("tgt.ShipmentID"),
            "left_anti"
        )
    )


    # ========================================================
    # EXISTING RECORDS
    # ========================================================

    existing_df = (
        source_df.alias("src")
        .join(
            target_df.alias("tgt"),
            col("src.ShipmentID")
            ==
            col("tgt.ShipmentID"),
            "inner"
        )
    )


    # ========================================================
    # CHANGE DETECTION
    # ========================================================

    change_condition = None

    for column_name in COMPARE_COLUMNS:

        condition = ~(
            col(
                f"src.{column_name}"
            ).eqNullSafe(
                col(
                    f"tgt.{column_name}"
                )
            )
        )

        if change_condition is None:

            change_condition = condition

        else:

            change_condition = (
                change_condition
                |
                condition
            )


    # ========================================================
    # UPDATED RECORDS
    # ========================================================

    updated_existing_df = (
        existing_df
        .filter(change_condition)
    )

    updated_df = (
        updated_existing_df
        .select("src.*")
    )


    # ========================================================
    # BUILD DETAILED CHANGE HISTORY
    # ========================================================

    change_history_df = None

    for column_name in COMPARE_COLUMNS:

        column_changes = (
            updated_existing_df
            .select(
                col("src.ShipmentID").alias("ShipmentID"),
                col(f"tgt.{column_name}")
                .cast("string")
                .alias("OldValue"),
                col(f"src.{column_name}")
                .cast("string")
                .alias("NewValue")
            )
            .filter(
                ~col("OldValue").eqNullSafe(
                    col("NewValue")
                )
            )
            .withColumn(
                "ColumnName",
                lit(column_name)
            )
            .select(
                "ShipmentID",
                "ColumnName",
                "OldValue",
                "NewValue"
            )
        )

        if change_history_df is None:

            change_history_df = column_changes

        else:

            change_history_df = (
                change_history_df
                .unionByName(column_changes)
            )


    # ========================================================
    # UNCHANGED
    # ========================================================

    unchanged_df = (
        existing_df
        .filter(~change_condition)
        .select("src.*")
    )


    # ========================================================
    # COUNTS
    # ========================================================

    inserted_count = inserted_df.count()

    updated_count = updated_df.count()

    unchanged_count = unchanged_df.count()


    # ========================================================
    # OLD RECORDS NOT PRESENT IN SOURCE
    # ========================================================

    old_records_to_keep = (
        target_df.alias("tgt")
        .join(
            source_df.alias("src"),
            col("tgt.ShipmentID")
            ==
            col("src.ShipmentID"),
            "left_anti"
        )
    )


    # ========================================================
    # FINAL DATASET
    # ========================================================

    final_df = (
        old_records_to_keep
        .unionByName(
            inserted_df
        )
        .unionByName(
            updated_df
        )
        .unionByName(
            unchanged_df
        )
    )


    return (
        final_df,
        inserted_count,
        updated_count,
        unchanged_count,
        change_history_df
    )


# ============================================================
# 20. WRITE PARQUET
# ============================================================

def write_parquet(
    df,
    output_folder
):

    record_count = df.count()

    print()
    print(
        f"Writing {record_count} records to:"
    )

    print(output_folder)


    # ========================================================
    # SMALL DATASET
    # ========================================================

    if record_count <= PARTITION_THRESHOLD:

        print(
            "Dataset is small -> "
            "using 1 partition."
        )

        df = df.coalesce(1)


    # ========================================================
    # LARGE DATASET
    # ========================================================

    else:

        print(
            "Dataset is large -> "
            f"using {LARGE_DATASET_PARTITIONS} "
            "partitions."
        )

        df = df.repartition(
            LARGE_DATASET_PARTITIONS
        )


    # ========================================================
    # WRITE
    # ========================================================

    (
        df.write
        .mode("overwrite")
        .parquet(
            str(output_folder)
        )
    )


# ============================================================
# 21. TEMP / FINAL PATHS
# ============================================================

temp_target = (
    TEMP_ROOT
    / f"target_{RUN_ID}"
)

temp_invalid = (
    TEMP_ROOT
    / f"invalid_{RUN_ID}"
)

final_target_version = (
    TARGET_VERSIONS_FOLDER
    / f"run_{RUN_ID}"
)

final_invalid_version = (
    INVALID_VERSIONS_FOLDER
    / f"run_{RUN_ID}"
)


# ============================================================
# 22. COUNTERS
# ============================================================

inserted_count = 0

updated_count = 0

unchanged_count = 0

valid_count = 0

invalid_count = 0


# ============================================================
# 23. MAIN ETL
# ============================================================

try:

    # ========================================================
    # STEP 1
    # READ SOURCE
    # ========================================================

    source_df = read_source()


    # ========================================================
    # STEP 2
    # TRANSFORM
    # ========================================================

    transformed_df = transform_data(
        source_df
    )


    # ========================================================
    # STEP 3
    # VALID / INVALID
    # ========================================================

    valid_df = transformed_df.filter(
        col("WeightStatus")
        ==
        "Valid"
    )

    invalid_df = transformed_df.filter(
        col("WeightStatus")
        ==
        "Invalid"
    )


    valid_count = valid_df.count()

    invalid_count = invalid_df.count()


    print()
    print("Validation results:")

    print(
        f"Valid records  : {valid_count}"
    )

    print(
        f"Invalid records: {invalid_count}"
    )


    # ========================================================
    # STEP 4
    # FIND CURRENT TARGET
    # ========================================================

    current_target = (
        get_current_target_folder()
    )


    # ========================================================
    # STEP 5
    # READ EXISTING TARGET
    # ========================================================

    existing_target_df = (
        read_existing_target(
            current_target
        )
    )


    # ========================================================
    # STEP 6
    # SCHEMA COMPATIBILITY
    # ========================================================

    if existing_target_df is not None:

        compatible = (
            target_schema_is_compatible(
                existing_target_df
            )
        )

        if not compatible:

            # Important:
            #
            # The old target came from the old
            # 5-column version.
            #
            # We cannot safely compare the new
            # 8-column source against it.
            #
            # Therefore use current source as
            # the new baseline.

            existing_target_df = None


    # ========================================================
    # STEP 7
    # INCREMENTAL PROCESSING
    # ========================================================

    (
        final_df,
        inserted_count,
        updated_count,
        unchanged_count,
        change_history_df
    ) = process_incremental(
        valid_df,
        existing_target_df
    )


    print()
    print("Incremental results:")

    print(
        f"Inserted  : {inserted_count}"
    )

    print(
        f"Updated   : {updated_count}"
    )

    print(
        f"Unchanged : {unchanged_count}"
    )


    # ========================================================
    # STEP 8
    # WRITE TARGET TO TEMP
    # ========================================================

    if temp_target.exists():

        shutil.rmtree(
            temp_target,
            ignore_errors=True
        )


    write_parquet(
        final_df,
        temp_target
    )


    # ========================================================
    # SAVE CHANGE HISTORY
    # ========================================================

    if change_history_df is not None:

        change_rows = [
            row.asDict()
            for row in change_history_df.collect()
        ]

        save_change_history(change_rows)

    else:

        print(
            "No detailed changes detected."
        )


    # ========================================================
    # STEP 9
    # WRITE INVALID RECORDS
    # ========================================================

    if temp_invalid.exists():

        shutil.rmtree(
            temp_invalid,
            ignore_errors=True
        )


    if invalid_count > 0:

        write_parquet(
            invalid_df,
            temp_invalid
        )

    else:

        print(
            "No invalid records found."
        )


    # ========================================================
    # STEP 10
    # STOP SPARK
    # ========================================================

    print()
    print(
        "Stopping Spark before "
        "promoting output..."
    )

    spark.stop()

    spark = None


    # ========================================================
    # STEP 11
    # PROMOTE TARGET
    # ========================================================

    print()
    print(
        "Promoting new target version..."
    )

    if final_target_version.exists():

        shutil.rmtree(
            final_target_version,
            ignore_errors=True
        )


    # IMPORTANT:
    #
    # We rename only the NEW temporary folder.
    #
    # We do NOT touch target_shipments.
    #

    os.rename(
        temp_target,
        final_target_version
    )


    print(
        "New target version:"
    )

    print(
        final_target_version
    )


    # ========================================================
    # STEP 12
    # PROMOTE INVALID VERSION
    # ========================================================

    print()
    print(
        "Promoting invalid-record version..."
    )

    if invalid_count > 0:

        if final_invalid_version.exists():

            shutil.rmtree(
                final_invalid_version,
                ignore_errors=True
            )

        os.rename(
            temp_invalid,
            final_invalid_version
        )

        print(
            "New invalid-record version:"
        )

        print(
            final_invalid_version
        )

    else:

        print(
            "No invalid-record version to promote."
        )


    # ========================================================
    # STEP 13
    # UPDATE POINTERS
    # ========================================================

    print()
    print(
        "Updating latest target pointer..."
    )

    write_pointer(
        LATEST_TARGET_POINTER,
        final_target_version
    )

    if invalid_count > 0:

        write_pointer(
            LATEST_INVALID_POINTER,
            final_invalid_version
        )

    elif LATEST_INVALID_POINTER.exists():

        LATEST_INVALID_POINTER.unlink()


    # ========================================================
    # STEP 14
    # CLEAN OLD VERSIONS
    # ========================================================

    cleanup_old_versions(
        TARGET_VERSIONS_FOLDER,
        VERSION_RETENTION
    )

    cleanup_old_versions(
        INVALID_VERSIONS_FOLDER,
        VERSION_RETENTION
    )


    # ========================================================
    # STEP 15
    # AUDIT
    # ========================================================

    end_time = datetime.now()

    duration = (
        end_time - START_TIME
    ).total_seconds()


    update_audit(
        status="SUCCESS",
        inserted=inserted_count,
        updated=updated_count,
        unchanged=unchanged_count,
        valid=valid_count,
        invalid=invalid_count,
        duration=duration
    )


    cleanup_old_audit_logs()


    # ========================================================
    # FINAL OUTPUT
    # ========================================================

    print()
    print("=" * 70)

    print(
        "ETL COMPLETED SUCCESSFULLY"
    )

    print("=" * 70)

    print(
        f"Run ID            : {RUN_ID}"
    )

    print(
        f"Inserted Records  : "
        f"{inserted_count}"
    )

    print(
        f"Updated Records   : "
        f"{updated_count}"
    )

    print(
        f"Unchanged Records: "
        f"{unchanged_count}"
    )

    print(
        f"Valid Records     : "
        f"{valid_count}"
    )

    print(
        f"Invalid Records   : "
        f"{invalid_count}"
    )

    print(
        f"Duration Seconds  : "
        f"{duration:.2f}"
    )

    print()

    print("Latest target:")

    print(
        final_target_version
    )

    print("=" * 70)


# ============================================================
# 24. ERROR HANDLING
# ============================================================

except Exception:

    error_text = traceback.format_exc()


    print()
    print("=" * 70)

    print("ETL FAILED")

    print("=" * 70)

    print(error_text)


    # ========================================================
    # STOP SPARK
    # ========================================================

    try:

        if spark is not None:

            spark.stop()

    except Exception:

        pass


    # ========================================================
    # CLEAN TEMP TARGET
    # ========================================================

    try:

        if temp_target.exists():

            shutil.rmtree(
                temp_target,
                ignore_errors=True
            )

    except Exception:

        pass


    # ========================================================
    # CLEAN TEMP INVALID
    # ========================================================

    try:

        if temp_invalid.exists():

            shutil.rmtree(
                temp_invalid,
                ignore_errors=True
            )

    except Exception:

        pass


    # ========================================================
    # AUDIT FAILURE
    # ========================================================

    try:

        end_time = datetime.now()

        duration = (
            end_time - START_TIME
        ).total_seconds()


        update_audit(
            status="FAILED",
            inserted=inserted_count,
            updated=updated_count,
            unchanged=unchanged_count,
            valid=valid_count,
            invalid=invalid_count,
            duration=duration,
            error_message=error_text
        )

    except Exception as audit_error:

        print(
            "Could not update failure audit:"
        )

        print(audit_error)


    # ========================================================
    # RETURN NON-ZERO EXIT STATUS
    # ========================================================

    raise

export_audit_csvs()